"""JobLens 结构化数据模型。"""

from .common import DateRange, SourceReference, StrictBaseModel
from .job import (
    AvailabilityRequirement,
    CompanyInformation,
    EducationDegree as JobEducationDegree,
    EmploymentType,
    ExperienceLevel,
    JobBasicInformation,
    JobBenefit,
    JobData,
    JobParseMetadata,
    JobParseResult,
    JobParseWarning,
    JobRequirement,
    JobResponsibility,
    MatchMode,
    ProficiencyLevel,
    RequirementCategory,
    RequirementImportance,
    SalaryPeriod,
    SalaryRange,
    WorkMode,
)
from .match import (
    BatchEvidenceMatchResult,
    ConstraintCheck,
    EvidenceCandidate,
    EvidenceMatchResult,
    EvidenceMatchStatus,
    EvidenceMatchSummary,
    EvidencePolarity,
    EvidenceSection,
    MatchDecisionMethod,
    RankedJobMatch,
    RequirementEvidenceMatch,
)
from .resume import ResumeData, ResumeParseResult

__all__ = [
    "AvailabilityRequirement",
    "BatchEvidenceMatchResult",
    "CompanyInformation",
    "ConstraintCheck",
    "DateRange",
    "EmploymentType",
    "EvidenceCandidate",
    "EvidenceMatchResult",
    "EvidenceMatchStatus",
    "EvidenceMatchSummary",
    "EvidencePolarity",
    "EvidenceSection",
    "ExperienceLevel",
    "JobBasicInformation",
    "JobBenefit",
    "JobData",
    "JobEducationDegree",
    "JobParseMetadata",
    "JobParseResult",
    "JobParseWarning",
    "JobRequirement",
    "JobResponsibility",
    "MatchMode",
    "MatchDecisionMethod",
    "ProficiencyLevel",
    "RankedJobMatch",
    "RequirementCategory",
    "RequirementImportance",
    "RequirementEvidenceMatch",
    "ResumeData",
    "ResumeParseResult",
    "SalaryPeriod",
    "SalaryRange",
    "SourceReference",
    "StrictBaseModel",
    "WorkMode",
]
